### ISSUE TITLE
Stackoverflow when set VET.Active to True

### ISSUE THREAD

**Issue by raelb** [pyscripter/MustangpeakVirtualShellTools#17] opened 2019-02-18 01:20 UTC
Hello,

I have just installed VirtualShellTools into Delphi Tokyo (10.2.3) on Windows 10. (It was installed via the Pyscripter Thirdparty MultiInstaller.exe).

In a blank project with VirtualExplorerTree, if I set VET.Active to True, I get a Stackoverflow error.

When I press break, it stops here:
![image](https://user-images.githubusercontent.com/13108198/52922640-2d695980-332b-11e9-901e-557f87841316.png)

![image](https://user-images.githubusercontent.com/13108198/52922725-095a4800-332c-11e9-8b69-d26a1651cf70.png)

Same error on 64 bit or 32 Bit
![image](https://user-images.githubusercontent.com/13108198/52922704-cd26e780-332b-11e9-9f8f-f86326a6f7ac.png)

Any ideas?

**Comment by pyscripter** [comment] 2019-02-18 13:57
Thanks I will look into it.
Just to make sure.  Are these the steps to reproduce?
1.  New VCL project
2.  Drop a VET on the form
3. On formshow you set VET.Active := True

and then the error occurs??

Rather suprising since I am using VET in a similar manner without such problems.

**Comment by raelb** [comment] 2019-02-18 16:02
Yes.

I did not actually do `VET.Active := True` in FormShow.

But I tried in a button click or in FormCreate, and problem occurs.

**Comment by pyscripter** [comment] 2019-02-18 16:28
Just tried in Delphi 10.3 both win32 and win64.  Default options.  Active works both in design and run time.

- Do you have anything unusual in your desktop? (e.g. Bluetooth foloder)
- What happens if you change the RootFolder to something else.

**Comment by raelb** [comment] 2019-02-19 05:22
1) No. I suppose the only thing unusual is that it is a VMWare VM.
2) Same problem.

Can you upload the binaries of your simple test application? That way I can
determine it is the machine and not some Delphi issue..

**Comment by pyscripter** [comment] 2019-02-25 00:53
[SpTBXFlicker.zip](https://github.com/pyscripter/MustangpeakVirtualShellTools/files/2898628/SpTBXFlicker.zip)
The attached 64 bit executable shows among other things an active VET.

**Comment by raelb** [comment] 2019-02-25 14:14
Yeah, it works fine as does PyScripter.
I'm baffled why it does not work for me.

**Comment by pyscripter** [comment] 2019-02-25 15:34
Have you got the latest version of all related libraries? (VirtualTree, Mustangpeak Common Library)?

**Comment by raelb** [comment] 2019-02-25 15:57
I did a clean install of all Pyscripter dependencies using MultiInstaller
yesterday...

**Comment by pyscripter** [comment] 2019-03-05 01:10
I think this is duplicate of  #18 which was fixed.

**Closed by pyscripter** 2019-03-05 01:10 UTC

**Comment by pyscripter** [comment] 2019-03-05 01:13
This was a result of Virtual-TreeView/Virtual-TreeView@467f9ee to which I objected. I knew it would cause problems.  The reason I could not reproduce the problem was that I was using an older version of VT.
